-- load configs for packer plugins
require("plugins.build")
require("plugins.indent-blankline")
require("plugins.bufferline")
require("plugins.statusline")
require("plugins.web-devicons")
require("plugins.which")
require("plugins.swagger")
require("plugins.autopairs")
require("plugins.nvimTree")
require("plugins.treesitter")
require("plugins.lspsaga")
