---@meta

---@class BASE_30
---@field white string
---@field darker_black string
---@field black string
---@field black2 string
---@field one_bg string
---@field one_bg2 string
---@field one_bg3 string
---@field grey string
---@field grey_fg string
---@field grey_fg2 string
---@field light_grey string
---@field red string
---@field baby_pink string
---@field pink string
---@field line string
---@field green string
---@field vibrant_green string
---@field nord_blue string
---@field blue string
---@field yellow string
---@field sun string
---@field purple string
---@field dark_purple string
---@field teal string
---@field orange string
---@field cyan string
---@field statusline_bg string
---@field lightbg string
---@field lightbg2 string
---@field pmenu_bg string
---@field folder_bg string

---@class BASE_16
---@field base00 string
---@field base01 string
---@field base02 string
---@field base03 string
---@field base04 string
---@field base05 string
---@field base06 string
---@field base07 string
---@field base08 string
---@field base09 string
---@field base0A string
---@field base0B string
---@field base0C string
---@field base0D string
---@field base0E string
---@field base0F string
