name: ci

on:
  workflow_dispatch:
    inputs:
      nvim-version:
        description: "use neovim (stable) or neovim-git (nightly)"
        default: "neovim"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    name: docker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push stable
        uses: docker/build-push-action@v2
        if: ${{ github.event.inputs.nvim-version  == 'neovim' }}
        with:
          context: .
          push: true
          build-args:
            - version=${{ github.event.inputs.nvim-version }}
          tags: danielnehrig/nvim:latest
      -
        name: Build and push nightly
        uses: docker/build-push-action@v2
        if: ${{ github.event.inputs.nvim-version  == 'neovim-git' }}
        with:
          context: .
          push: true
          build-args:
            - version=${{ github.event.inputs.nvim-version }}
          tags: danielnehrig/nvim:nightly
