name: Lint

on: 
  push:
    branches:
      - master
  pull_request:
    types: [opened]

jobs:
    lint:
        name: Luacheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup
              run: |
                  sudo apt-get update
                  sudo apt-get install luarocks
                  sudo luarocks install luacheck
            - name: Lint
              run: luacheck lua --globals vim packer_plugins IS_NVIM --no-max-line-length
